name: pydata
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - requests
  - xlrd
  - openpyxl
  - seaborn 
  - langchain 
  - pip:
    - tqdm
    - unidecode
    - tiktoken
    - openai
    - scikit-learn
    - chromadb